const token = {
  IDENTIFIER: 0,
  STRING: 1,
  INTEGER: 2,
  FLOAT: 3,
  OPERATOR_PLUS: 4,
  OPERATOR_MINUS: 5,
  OPERATOR_TIMES: 6,
  OPERATOR_DIVIDE: 7,
  KEYWORD: 8,
  INVALID: 9,
  ASSIGNMENT_OPERATOR: 10,
  SEMICOLON: 11,
  LEFT_PARENTHESIS: 12,
  RIGHT_PARENTHESIS: 13,
  COMMA: 14,
  DOT: 15,
  DOTDOT: 16,
  COLON: 17,
  EQUAL: 18,
  LOWER_OR_EQUALS: 19,
  GREATER_OR_EQUALS: 20,
  NOT_EQUALS: 21,
  GREATER_THAN: 22,
  LOWER_THAN: 23,
  AT_SIGN: 24,
  LEFT_BRACE: 25,
  RIGHT_BRACE: 26,
};

Object.freeze(token);

export default token;
